pub fn extension_to_mime(extension: &str) -> &str {
    match extension {
        "js" => "text/javascript",
        "html" | "htm" => "text/html",
        "css" => "text/css",
        "jpeg" | "jpg" => "image/jpeg",
        "png" => "image/png",
        "gif" => "image/gif",
        "bmp" => "image/bmp",
        "json" => "application/json",
        "mjs" => "text/javascript",
        "mp3" => "audio/mpeg",
        "mp4" => "video/mp4",
        "mov" => "video/quicktime",
        "mpeg" => "video/,peg",
        "php" => "application/x-httpd-php",
        "txt" => "text/plain",
        "weba" => "audio/webm",
        "webm" => "video/webm",
        "webp" => "image/webp",
        "xml" => "application/xml",
        "zip" => "application/zip",
        "7z" => "application/x-7z-compressed",
        "tar" => "application/x-tar",
        "gz" => "application/gzip",
        _ => "application/octet-stream",
    }
}